#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org
START=50

USE_PROCD=1
PROG="/usr/sbin/snmpd"

CONFIGFILE="/etc/snmpd/snmpd.conf"

start_service() {

	procd_open_instance

	procd_set_param command $PROG \
                -c $CONFIGFILE \
		-f \
		-LSwd
	procd_set_param respawn ${respawn_retry:-3} ${respawn_threshold:60} ${respawn_timeout:-10}
        procd_set_param file $CONFIGFILE

	procd_close_instance
}
